// server.js
import http, { get } from "http";
import "dotenv/config";
import mariadb from "mariadb";
import https from "https";
import fs from "fs";
import crypto, { privateDecrypt } from "crypto";
import Utf8Stream from "fs";
import { deserialize } from "v8";
import { networkInterfaces } from "os";
import { decrypt } from "dotenv";

//encryption

//takes utf8 plaintext and arraybuffer key
// returns base64 iv and ciphertext/authtag (appended together)
async function encryptAESGCM(plaintext, key) {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);

  const ciphertextbuf = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);
  const ctAndAuth = Buffer.concat([ciphertextbuf, cipher.getAuthTag()]);

  return {
    backiv: iv.toString("base64"),
    backciphertext: ctAndAuth.toString("base64"),
  };
}
//generated by AI
function b64ToBytes(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);

  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  return bytes;
}

//debug function
function toHex(bytes) {
  return Buffer.from(bytes).toString("hex");
}
//takes base64 ciphertext b64 passediv and arraybuffer/buffer key
//  returns utf8 strings
function decryptAESGCM(ciphertext, passediv, key) {
  const ivBuffer = Buffer.from(passediv, "base64");
  const ctnauthBuffer = Buffer.from(ciphertext, "base64");

  const ctBuf = ctnauthBuffer.subarray(0, ctnauthBuffer.length - 16);
  const authBuf = ctnauthBuffer.subarray(ctnauthBuffer.length - 16);

  const decipherIV = crypto.createDecipheriv("aes-256-gcm", key, ivBuffer);
  decipherIV.setAuthTag(authBuf);
  try {
    const plaintextBuf = Buffer.concat([
      decipherIV.update(ctBuf),
      decipherIV.final(),
    ]);

    return plaintextBuf.toString("utf-8");
  } catch (err) {
    console.error("=== AES-GCM FAILURE ===");

    console.error({
      error: err.message,

      ivLength: ivBuffer.length,
      ctLength: ctBuf.length,
      authTagLength: authBuf.length,
      keyLength: key.length,

      ivHex: toHex(ivBuffer),
      authTagHex: toHex(authBuf),

      keyFingerprint: crypto
        .createHash("sha256")
        .update(Buffer.from(key))
        .digest("hex"),

      ctFingerprint: crypto.createHash("sha256").update(ctBuf).digest("hex"),
    });

    throw err;
  }
}

const pool = mariadb.createPool({
  host: "127.0.0.1",
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  connectionLimit: 5,
});

const PORT = 3000;
const server = https.createServer(
  //keys
  {
    key: fs.readFileSync("certs/key.pem"),
    cert: fs.readFileSync("certs/cert.pem"),
  },
  (req, res) => {
    // CORS
    res.setHeader("Access-Control-Allow-Origin", req.headers.origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");

    if (req.method === "OPTIONS") {
      res.writeHead(204);
      return res.end();
    }

    if (req.method === "GET" && req.url === "/api/health") {
      res.writeHead(200, { "Content-Type": "application/json" });
      return res.end(JSON.stringify({ ok: true }));
    }

    if (req.method === "POST" && req.url === "/api/logout") {
      let body = "";

      req.on("data", (chunk) => {
        body += chunk;
      });

      req.on("end", async () => {
        const dataEncrypted = JSON.parse(body);
        const cookieJSON = parseCookie(req.headers.cookie);
        const netKey = await getNetKey(cookieJSON.netSession);
        const data = decryptAESGCM(
          dataEncrypted.encrypted.frontciphertext,
          dataEncrypted.encrypted.frontiv,
          netKey,
        );
        let responseData = {};
        const logoutResult = await delLogSession(cookieJSON.logSession);
        if (logoutResult) {
          responseData.message = "logged out";
          res.setHeader(
            "Set-Cookie",
            `session=; HttpOnly; Path=/; SameSite=None; Secure; Max-Age=0`,
          );
        } else {
          console.log("errorlogout");
        }
        res.writeHead(200, { "Content-Type": "application/json" });
        responseData.success = true;
        res.end(JSON.stringify(responseData));
        console.log("logged out");
      });
      return;
    }
    if (req.method === "POST" && req.url === "/api/account") {
      let body = "";

      req.on("data", (chunk) => {
        body += chunk;
      });

      req.on("end", async () => {
        const encryptedData = JSON.parse(body);
        let responseData = {};
        const cookieJSON = parseCookie(req.headers.cookie);

        const keys = await getNetAndUserKey(
          cookieJSON.netSession,
          cookieJSON.logSession,
        );

        const data = JSON.parse(
          decryptAESGCM(
            encryptedData.encrypted.frontciphertext,
            encryptedData.encrypted.frontiv,
            keys.netkey,
          ),
        );

        const ptUser = decryptAESGCM(
          data.Email.frontciphertext,
          data.Email.frontiv,
          keys.logkey,
        );
        const ptPass = decryptAESGCM(
          data.Password.frontciphertext,
          data.Password.frontiv,
          keys.logkey,
        );

        // login path
        if (data.Action === "login") {
          //login function validates credentials returns the user id if successful, otherwise returns -1 for wrong pass and -2 for username dne
          const loginResult = await login(ptUser, ptPass);
          if (loginResult != -1 && loginResult != -2) {
            responseData.message = "logged in";
            await addUser2Session(loginResult, cookieJSON.logSession);
            const score = await getHighScore(cookieJSON.logSession);
            responseData.curHighScore = await encryptAESGCM(
              score.toString(),
              keys.logkey,
            );
            res.setHeader(
              "Set-Cookie",
              `session=${loginResult}; HttpOnly; Path=/; SameSite=None; Secure`,
            );
          } else if (loginResult == -1) {
            responseData.message = "wrong pass";
          } else if (loginResult == -2) {
            responseData.message = "username dne";
          } else {
            console.log("errorlogin");
          }
          //if username dne is returned is creates an account and notifies the user, if
        } else if (data.Action === "create") {
          // create account path
          const checkResult = await checkExistingUsers(ptUser);
          if (checkResult) {
            responseData.message = "username exists";
          } else {
            await createAccount(ptUser, ptPass);
            responseData.message = "account created";
          }
          //The tls session created when trying to make an account exists only for the creation, deleted immediately after and a new session is made when logging in
          delLogSession(cookieJSON.logSession);
        } else {
          console.log("invalid action");
        }

        res.writeHead(200, { "Content-Type": "application/json" });
        responseData.success = true;
        const encryptedresponseData = await encryptAESGCM(
          JSON.stringify(responseData),
          keys.netkey,
        );
        res.write(JSON.stringify({ encrypted: encryptedresponseData }));

        res.end();
      });

      return;
    }
    if (req.method === "POST" && req.url === "/api/writescore") {
      let body = "";

      req.on("data", (chunk) => {
        body += chunk;
      });
      req.on("end", async () => {
        const encryptedData = JSON.parse(body);
        const cookieJSON = parseCookie(req.headers.cookie);
        const keys = await getNetAndUserKey(
          cookieJSON.netSession,
          cookieJSON.logSession,
        );
        const data = JSON.parse(
          decryptAESGCM(
            encryptedData.encrypted.frontciphertext,
            encryptedData.encrypted.frontiv,
            keys.netkey,
          ),
        );

        console.log(data);

        const score = decryptAESGCM(
          data.frontciphertext,
          data.frontiv,
          keys.logkey,
        );
        console.log(score);

        res.writeHead(200, { "Content-Type": "application/json" });
        const updateResult = await updateHighScore(
          cookieJSON.logSession,
          score,
        );
        if (updateResult) {
          res.end(JSON.stringify({ success: true, message: "Score updated" }));
        } else {
          res.end(
            JSON.stringify({
              success: false,
              message: "Failed to update score",
            }),
          );
        }
      });
      return;
    }
    if (req.method === "POST" && req.url === "/api/TLSHandshake") {
      let body = "";
      req.on("data", (chunk) => {
        body += chunk.toString();
      });
      req.on("end", async () => {
        const DHObject = crypto.createECDH("prime256v1");
        DHObject.generateKeys();
        let sharedSecret = null;
        let messageTranscript = "";
        let keyBuffer = null;
        let responseData = {};
        messageTranscript += body;
        let data = JSON.parse(body);
        let cookieJSON = {};

        try {
          cookieJSON = parseCookie(req.headers.cookie);
        } catch (error) {
          console.log("error could not parse cookies");
        }

        if (data.hasOwnProperty("encrypted")) {
          const netsessionKey = await getNetKey(cookieJSON.netSession);
          const temp = decryptAESGCM(
            data.encrypted.frontciphertext,
            data.encrypted.frontiv,
            netsessionKey,
          );

          data = JSON.parse(temp);
        }
        if (data.Handshake === "ClientHello") {
          responseData.Handshake = "ServerHello";
          responseData.ServerPublicKey = DHObject.getPublicKey("base64"); // Send server's public key to client
          responseData.ServerRandom = crypto.randomUUID();
          const sharedSecret = DHObject.computeSecret(
            data.ClientPublicKey,
            "base64",
          );
          messageTranscript += JSON.stringify(responseData);

          const salt = Buffer.from(messageTranscript, "utf8");
          const info = Buffer.from(data.SessionType, "utf8");
          keyBuffer = crypto.hkdfSync("SHA-512", sharedSecret, salt, info, 32);
          if (data.SessionType == "net") {
            const netSession = await createSessionNetwork(keyBuffer);
            res.setHeader(
              "Set-Cookie",
              `netSession=${netSession}; HttpOnly; Path=/; SameSite=None; Secure`,
            );
          } else if (data.SessionType == "log") {
            const logSession = await createSessionUser(null, keyBuffer);
            await addLog2Net(logSession, cookieJSON.netSession);
            res.setHeader(
              "Set-Cookie",
              `logSession=${logSession}; HttpOnly; Path=/; SameSite=None; Secure`,
            );
          } else {
            console.log("session error");
          }
        }

        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(responseData));
      });

      return;
    }

    // fallback 404 for unknown routes
    res.writeHead(404, { "Content-Type": "application/json" });
    return res.end(JSON.stringify({ error: "Not found" }));
  },
);

server.listen(PORT, "192.168.20.15", () => {
  console.log(`Server running at https://192.168.20.15:${PORT}`);
});

async function createAccount(username, password) {
  const conn = await pool.getConnection();
  try {
    await conn.query(
      "INSERT INTO users (username, password_hash, highscore) VALUES (?, ?, ?)",
      [username, password, 0],
    );
  } finally {
    conn.release();
  }
}

async function login(username, password) {
  const conn = await pool.getConnection();
  try {
    const dbRes = await conn.query(
      "SELECT id,username,password_hash FROM users WHERE username = ?",
      [username],
    );
    if (dbRes.length > 0) {
      if (dbRes[0].password_hash == password) {
        return dbRes[0].id;
      } else {
        return -1;
      }
    } else {
      return -2;
    }
  } finally {
    conn.release();
  }
}

async function getUserId(sessionId) {
  const conn = await pool.getConnection();
  try {
    const dbRes = await conn.query(
      "SELECT user_id FROM logsessions WHERE session_hash = ?",
      [sessionId],
    );
    return dbRes[0].user_id;
  } finally {
    conn.release();
  }
}
async function getHighScore(sessionId) {
  const conn = await pool.getConnection();

  try {
    const dbRes = await conn.query(
      "SELECT highscore FROM users JOIN logsessions ON users.id = logsessions.user_id WHERE logsessions.session_hash = ?",
      [sessionId],
    );
    return dbRes[0].highscore;
  } finally {
    conn.release();
  }
}
async function updateHighScore(sessionId, score) {
  const conn = await pool.getConnection();
  try {
    await conn.query(
      "UPDATE users JOIN logsessions ON users.id = logsessions.user_id SET highscore = ? WHERE logsessions.session_hash = ?",
      [score, sessionId],
    );
    return true;
  } finally {
    conn.release();
  }
}
async function delLogSession(sessionId) {
  const conn = await pool.getConnection();
  try {
    await conn.query("DELETE FROM logsessions WHERE session_hash = ?", [
      sessionId,
    ]);
    return true;
  } finally {
    conn.release();
  }
}

async function createSessionUser(userId, userKey) {
  const conn = await pool.getConnection();
  const userKeyBuf = Buffer.from(userKey);
  try {
    const sessionId = crypto.randomUUID();
    await conn.query(
      "INSERT INTO logsessions (user_id, session_hash, logaeskey) VALUES (?, ?,?)",
      [userId, sessionId, userKeyBuf],
    );
    return sessionId;
  } finally {
    conn.release();
  }
}
async function createSessionNetwork(netKey) {
  const conn = await pool.getConnection();
  const netKeyBuf = Buffer.from(netKey);
  try {
    const sessionId = crypto.randomUUID();
    await conn.query(
      "INSERT INTO netsessions (netsessionid, netaeskey) VALUES (?,?)",
      [sessionId, netKeyBuf],
    );
    return sessionId;
  } finally {
    conn.release();
  }
}
async function getNetKey(netSession) {
  const conn = await pool.getConnection();
  try {
    const netKey = await conn.query(
      "SELECT netaeskey FROM netsessions WHERE netsessionid = ?",
      [netSession],
    );
    return netKey[0].netaeskey;
  } finally {
    conn.release();
  }
}
async function getNetAndUserKey(netsession, logsession) {
  const conn = await pool.getConnection();
  try {
    const keys = await conn.query(
      "SELECT netsessions.netaeskey, logsessions.logaeskey FROM netsessions JOIN logsessions ON netsessions.logsessionid = logsessions.session_hash WHERE netsessions.netsessionid = ?",
      [netsession],
    );
    return { netkey: keys[0].netaeskey, logkey: keys[0].logaeskey };
  } finally {
    conn.release();
  }
}

function parseCookie(cookieString) {
  const cookieArray = cookieString.split("; ");
  let cookieReturn = {};
  for (const cook of cookieArray) {
    const cookPair = cook.split("=");
    cookieReturn[cookPair[0]] = cookPair[1];
  }
  return cookieReturn;
}

async function addUser2Session(userId, logsession) {
  const conn = await pool.getConnection();
  try {
    await conn.query(
      "UPDATE logsessions SET user_id = ? WHERE logsessions.session_hash = ?",
      [userId, logsession],
    );
  } finally {
    conn.release();
  }
}
async function addLog2Net(logsession, netsession) {
  const conn = await pool.getConnection();
  try {
    await conn.query(
      "UPDATE netsessions SET logsessionid = ? WHERE netsessions.netsessionid = ?",
      [logsession, netsession],
    );
  } finally {
    conn.release();
  }
}

async function checkExistingUsers(username) {
  const conn = await pool.getConnection();
  try {
    const dbRes = await conn.query(
      "SELECT EXISTS(SELECT 1 FROM users WHERE username = ?) AS exists_flag",
      [username],
    );
    if (dbRes[0].exists_flag === 1) {
      return true;
    } else {
      return false;
    }
  } finally {
    conn.release();
  }
}
